name: Format Available Resources

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run Prettier
      run: npx prettier --write "src/assets/translations/*.json"

    - name: Commit formatted JSON files
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout -b format-json-branch
        git add .
        git commit -m 'Format JSON files' || echo "No changes to commit"

    - name: Push changes to format-json-branch
      run: |
        git push origin format-json-branch

    - name: Create Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Ensure `gh` CLI is installed
        curl -fsSL https://cli.github.com/packages/githubcli.repo> /etc/apt/sources.list.d/github-cli.list
        sudo apt update
        sudo apt install gh

        # Authenticate with GitHub CLI using the token
        echo $GITHUB_TOKEN | gh auth login --with-token

        # Create the pull request
        gh pr create --title "Format JSON files" --body "This PR formats all JSON files." --base main --head format-json-branch
