name: Format Available Resources

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run Prettier
      run: npx prettier --write "src/assets/translations/*.json"

    - name: Commit formatted JSON files
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout -b format-json-branch
        git add .
        git commit -m 'Format JSON files' || echo "No changes to commit"

    - name: Push changes and create a pull request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin format-json-branch
        gh pr create --title "Format JSON files" --body "This PR formats all JSON files." --base main --head format-json-branch