name: Format Available Resources

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run Prettier
      run: npx prettier --write "src/assets/translations/*.json"

    - name: Push changes to auto-format-branch
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git checkout -b auto-format
        git add .
        git commit -m "Auto-format available resources" || echo "No changes to commit"
        git push --set-upstream origin auto-format
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Auto-format available resources"
        body: "This pull request contains auto-formatted changes to the available resources."
        base: main
        head: auto-format
